import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { PGlite } from "@electric-sql/pglite";
import ts from "typescript";
import { beforeAll, describe, expect, it } from "vitest";
import { createSchemaFromMigrations } from "./helpers/pg-platform";

/**
 * Guards `src/lib/supabase/database.types.ts` against the migrations (#269).
 *
 * That file is generated by hand with `npm run db:types` and committed, and
 * nothing checked that it still described the schema. It is the ground truth
 * for every typed query in `db/`: supabase-js derives the row type of a
 * `select` from it, so when it drifts, `tsc` keeps type-checking against a
 * schema that no longer exists and says nothing. #122 leaned on exactly that —
 * "remove the casts and tsc still passes" is only as good as this file.
 *
 * The issue weighed three ways to catch it, all of which pay something: a CI
 * job regenerating the types (needs a `SUPABASE_ACCESS_TOKEN` secret and a
 * network call per run), a committed marker naming the last migration the
 * types were generated from (needs a human to bump it), or regenerating on a
 * schedule (a signal, but late).
 *
 * There is a fourth now. The migrations can be applied to a real Postgres
 * compiled to wasm, and the schema they produce compared against the file —
 * no credentials, no network, nothing to remember. That option did not exist
 * when the issue was written; the harness arrived with #288.
 *
 * **What it compares.** Base tables and the columns of their `Row`, each
 * column's nullability and a coarse type class, and the functions PostgREST
 * exposes. That is the drift which actually breaks a typed query: a table or
 * column that appears, disappears, changes nullability, or turns from text
 * into a number.
 *
 * **What it does not — and these are not looked at at all, rather than looked
 * at loosely.** `Insert` and `Update` shapes, `Enums`, `Views`,
 * `CompositeTypes`, and the `Relationships` arrays. A regeneration that
 * changes only those passes here unnoticed. Two reasons, and the second is the
 * honest one: the exact TypeScript spelling would mean reimplementing
 * `supabase gen types` and keeping a guard bug-for-bug compatible with a
 * generator, and the rest is simply not built yet. If a `create view` or a
 * `create type ... as enum` lands in `public`, this file is where to extend
 * the comparison — it will not start failing to tell you.
 */

const TYPES_FILE = join(process.cwd(), "src/lib/supabase/database.types.ts");

const REGENERATE = "Run `npm run db:types` and commit the result.";

/** A class both sides can produce, or `null` to skip the comparison. */
type TypeClass = string | null;

interface Column {
  /** Coarse class, not the generated spelling. See `typeClass`. */
  cls: TypeClass;
  nullable: boolean;
}

/**
 * Postgres type to the class the generator would give it.
 *
 * Deliberately lossy: `text` and `uuid` and `timestamptz` are all `string` in
 * the generated file, and telling them apart here would only manufacture
 * failures the type system cannot see anyway. What it does keep is the
 * boundary that matters — a column that turns from text into a number, or
 * into json, changes what code can do with it.
 *
 * Enums need the extra argument. `information_schema` reports every enum,
 * domain and composite column as the literal string `USER-DEFINED`, with the
 * real name in `udt_name`, while the generator writes
 * `Database["public"]["Enums"]["mood"]`. Compared naively those two can never
 * agree, so the first enum anyone adds would fail this guard forever against a
 * perfectly correct file.
 *
 * **Anything else returns `null`, which skips the class comparison.** That
 * default is the point, and it was wrong three times before it was right: a
 * fallback of `return pgType` hands back a raw Postgres name — `bytea`,
 * `interval`, `oid` — that the generated file cannot contain under any
 * spelling, so the two sides could never agree and the first column of such a
 * type would block a correct schema forever. Each time the fix was a narrower
 * whitelist; each time another type fell outside it.
 *
 * So the rule is not "map everything", it is **claim a class only where both
 * sides can produce the same one, and say nothing otherwise**. A skipped class
 * still leaves presence and nullability checked, which is most of the value.
 * A guard that reports a difference that is not one gets switched off, and
 * then it guards nothing at all.
 */
function typeClass(pgType: string, udtName: string, enums: Set<string>): TypeClass {
  if (pgType === "USER-DEFINED") {
    return enums.has(udtName) ? `enum:${udtName}` : null;
  }
  if (/^(text|character|uuid|timestamp|date|time|citext|inet|name)/.test(pgType)) return "string";
  if (/^(integer|bigint|smallint|numeric|real|double|decimal)/.test(pgType)) return "number";
  if (pgType === "boolean") return "boolean";
  if (pgType.startsWith("json")) return "Json";
  if (pgType === "ARRAY") return "array";
  return null;
}

/**
 * The same class, read off the generated type node.
 *
 * Arrays are settled before enums, and the order is the whole point. Postgres
 * reports `mood[]` as `ARRAY` with the element in `udt_name`, so the database
 * side of this comparison says `array` and nothing about the element. An
 * unanchored enum match here would look straight through the trailing `[]` and
 * answer `enum:mood`, and the two would disagree forever on a column that is
 * perfectly correct — the same false positive the enum handling exists to
 * remove, reintroduced by the removal.
 *
 * **The enum spelling below is assumed, not observed.** No migration creates an
 * enum, so the committed file has an empty `Enums` block and there is no sample
 * to check against; `npm run db:types` needs credentials and a network.
 *
 * If the guess is wrong — an inline union of string literals, say — the fall
 * through at the end returns `null` and the column's class is simply not
 * compared, which is the failure worth having: quieter than it could be, never
 * wrong. To settle it: add a throwaway enum column, run the real `db:types`,
 * and read what it emitted.
 */
function tsClass(text: string): TypeClass {
  const bare = text.replace(/\s*\|\s*null\s*$/, "").trim();
  if (bare.endsWith("[]")) return "array";
  const enumRef = /\["Enums"\]\["([^"]+)"\]/.exec(bare);
  if (enumRef) return `enum:${enumRef[1]}`;
  // Same rule as `typeClass`, from the other side: name only what both can
  // produce. Without this the two functions have different vocabularies, and
  // a generated spelling neither anticipated reads as drift rather than as
  // something to go and look at.
  if (["string", "number", "boolean", "Json"].includes(bare)) return bare;
  return null;
}

/**
 * Whether two classes are a difference worth reporting.
 *
 * A `null` on either side ends the question, and the asymmetric case is the
 * one worth naming: a column changed from `text` to `bytea` leaves the
 * database side declining while the committed file still says `string`. That
 * is real drift, and it still goes unreported here — because `bytea` may well
 * generate as `string`, so calling it a difference would be a guess, and a
 * guess that fires on a correct file is how a guard gets switched off.
 *
 * Presence and nullability still cover that column, which is why the trade is
 * worth taking rather than merely tolerable. Extend `typeClass` if a type like
 * that arrives and the class matters.
 */
function classesDiffer(fromDatabase: TypeClass, fromTypes: TypeClass): boolean {
  if (fromDatabase === null || fromTypes === null) return false;
  return fromDatabase !== fromTypes;
}

function typeLiteralMembers(node: ts.TypeNode | undefined): ts.TypeElement[] {
  return node && ts.isTypeLiteralNode(node) ? [...node.members] : [];
}

function propertyName(member: ts.TypeElement): string {
  return member.name?.getText().replace(/["']/g, "") ?? "";
}

function property(node: ts.TypeNode | undefined, name: string): ts.TypeNode | undefined {
  const found = typeLiteralMembers(node).find(
    (m) => ts.isPropertySignature(m) && propertyName(m) === name,
  );
  // `found` is undefined whenever the property is absent, which is the normal
  // path — a non-null assertion here would crash on the first missing key.
  return found && ts.isPropertySignature(found) ? found.type : undefined;
}

/**
 * Reads the committed types through the TypeScript parser rather than a regex.
 *
 * The file is machine-generated and very regular, which is exactly what makes
 * a regex tempting and wrong: the day the generator changes its indentation,
 * a regex reports an empty schema and every assertion below passes.
 */
function readCommittedTypes() {
  const source = ts.createSourceFile(
    "database.types.ts",
    readFileSync(TYPES_FILE, "utf8"),
    ts.ScriptTarget.Latest,
    true,
  );

  const database = source.statements.find(
    (s): s is ts.TypeAliasDeclaration =>
      ts.isTypeAliasDeclaration(s) && s.name.text === "Database",
  );
  if (!database) throw new Error(`No \`Database\` type alias in ${TYPES_FILE}`);

  const publicSchema = property(database.type, "public");

  const tables = new Map<string, Map<string, Column>>();
  for (const table of typeLiteralMembers(property(publicSchema, "Tables"))) {
    if (!ts.isPropertySignature(table)) continue;
    const row = property(table.type, "Row");
    tables.set(
      propertyName(table),
      new Map(
        typeLiteralMembers(row)
          .filter(ts.isPropertySignature)
          .map((c) => [
            propertyName(c),
            { cls: tsClass(c.type!.getText()), nullable: /\|\s*null/.test(c.type!.getText()) },
          ]),
      ),
    );
  }

  const functions = new Set(
    typeLiteralMembers(property(publicSchema, "Functions")).map(propertyName),
  );

  return { tables, functions };
}

/**
 * The functions the generator would list, by the three rules that decide it.
 *
 * `distinct`, because two overloads of one name are two rows here and can only
 * ever be one key in a TypeScript object type — without it, adding a second
 * signature reports drift against a file that is correct.
 */
async function exposedFunctions(instance: PGlite): Promise<string[]> {
  const { rows } = await instance.query<{ proname: string }>(
    `select distinct p.proname
     from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public'
       and pg_get_function_result(p.oid) <> 'trigger'
       and (has_function_privilege('anon', p.oid, 'EXECUTE')
         or has_function_privilege('authenticated', p.oid, 'EXECUTE'))
     order by 1`,
  );
  return rows.map((r) => r.proname);
}

let db: PGlite;
let committed: ReturnType<typeof readCommittedTypes>;

beforeAll(async () => {
  db = await createSchemaFromMigrations();
  committed = readCommittedTypes();
});

describe("the comparison itself", () => {
  // Two ordinary schema changes would each have made this guard fail forever
  // against a perfectly correct file: an enum column, and a second signature
  // for one function name. Neither exists in the migrations today, so the
  // comparisons below them prove nothing about either — these do.

  it("agrees with the generator on an enum column", () => {
    // Postgres reports every enum column as the string USER-DEFINED, with the
    // name in `udt_name`; the generator writes a reference into `Enums`.
    // Compared naively the two can never match.
    const fromDatabase = typeClass("USER-DEFINED", "mood", new Set(["mood"]));
    const fromTypes = tsClass('Database["public"]["Enums"]["mood"] | null');

    expect(fromDatabase).toBe("enum:mood");
    expect(fromTypes).toBe(fromDatabase);
  });

  it("calls an array of enums an array, on both sides", () => {
    // The regression: an unanchored enum match read through the trailing `[]`
    // and answered `enum:mood`, while Postgres reports the column as `ARRAY`.
    // A column of type `mood[]` would have failed this guard forever.
    expect(typeClass("ARRAY", "_mood", new Set(["mood"]))).toBe("array");
    expect(tsClass('Database["public"]["Enums"]["mood"][] | null')).toBe("array");
  });

  it("says nothing when only one side can classify, on purpose", () => {
    // The asymmetric case, which is genuinely drift and genuinely unreported:
    // `text` -> `bytea` leaves the database declining while the committed file
    // still says `string`. Naming it a difference would be a guess — `bytea`
    // may generate as `string` — and presence and nullability still cover the
    // column. Written down as a decision rather than left to be rediscovered.
    expect(classesDiffer(null, "string")).toBe(false);
    expect(classesDiffer("string", null)).toBe(false);
    expect(classesDiffer(null, null)).toBe(false);
    // And the part that must still fire.
    expect(classesDiffer("string", "number")).toBe(true);
  });

  it("declines from the types side too, so the two share one vocabulary", () => {
    // The classifiers only ever name `string`, `number`, `boolean`, `Json`,
    // `array` or `enum:x`. Anything else is `null` on both sides rather than
    // a value the other could not possibly match.
    expect(tsClass("SomeUnanticipatedSpelling")).toBeNull();
    expect(tsClass('"a" | "b"')).toBeNull();
    expect(tsClass("Json")).toBe("Json");
  });

  it("says nothing about a type it cannot map, instead of guessing wrong", () => {
    // The regression, three times over: a fallback that returned the raw
    // Postgres name. `bytea` and `interval` and `oid` never appear in a
    // generated types file under any spelling, so the comparison could never
    // agree and the first such column would block a correct schema forever.
    const enums = new Set<string>();
    for (const pg of ["bytea", "interval", "oid", "tsvector", "point", "money"]) {
      expect(typeClass(pg, pg, enums), pg).toBeNull();
    }
  });

  it("declines to compare a domain rather than guessing", () => {
    // Not an enum, so nothing here can say what the generator resolved it to.
    // `null` means "skip the class", and presence and nullability still apply.
    expect(typeClass("USER-DEFINED", "postal_code", new Set(["mood"]))).toBeNull();
  });

  it("still tells text from number, which is the boundary that matters", () => {
    const enums = new Set<string>();
    expect(typeClass("text", "text", enums)).toBe("string");
    expect(typeClass("numeric", "numeric", enums)).toBe("number");
    expect(tsClass("string | null")).toBe("string");
    expect(tsClass("number")).toBe("number");
    expect(typeClass("ARRAY", "_text", enums)).toBe(tsClass("string[]"));
  });

  it("counts an overloaded function once, as the generated type must", async () => {
    const overloaded = await createSchemaFromMigrations();
    await overloaded.exec(`
      create function public.spike_overload(a integer) returns integer
        language sql as $$ select a $$;
      create function public.spike_overload(a text) returns text
        language sql as $$ select a $$;
    `);

    const names = await exposedFunctions(overloaded);
    expect(names.filter((n) => n === "spike_overload")).toHaveLength(1);
  });
});

describe("database.types.ts against the migrations", () => {
  it("applies every migration to a real Postgres", async () => {
    // If `createSchemaFromMigrations` threw, the suite never got here. This
    // asserts the schema is actually populated, because a stub that silently
    // produced nothing would make every comparison below vacuously pass.
    const { rows } = await db.query<{ n: number }>(
      `select count(*)::int as n from information_schema.tables
       where table_schema = 'public' and table_type = 'BASE TABLE'`,
    );
    expect(rows[0]!.n).toBeGreaterThan(10);
  });

  it("describes the same tables", async () => {
    const { rows } = await db.query<{ table_name: string }>(
      `select table_name from information_schema.tables
       where table_schema = 'public' and table_type = 'BASE TABLE'
       order by 1`,
    );
    const inDatabase = rows.map((r) => r.table_name);

    expect(inDatabase, REGENERATE).toEqual([...committed.tables.keys()].sort());
  });

  it("describes the same columns, nullability and type class", async () => {
    const { rows } = await db.query<{
      table_name: string;
      column_name: string;
      data_type: string;
      udt_name: string;
      is_nullable: string;
    }>(
      `select c.table_name, c.column_name, c.data_type, c.udt_name, c.is_nullable
       from information_schema.columns c
       join information_schema.tables t
         on t.table_schema = c.table_schema and t.table_name = c.table_name
       where c.table_schema = 'public' and t.table_type = 'BASE TABLE'
       order by 1, 2`,
    );

    // Enum type names, so a USER-DEFINED column can be told from a domain.
    const { rows: enumRows } = await db.query<{ typname: string }>(
      `select t.typname from pg_type t join pg_namespace n on n.oid = t.typnamespace
       where n.nspname = 'public' and t.typtype = 'e'`,
    );
    const enums = new Set(enumRows.map((r) => r.typname));

    const differences: string[] = [];
    const seen = new Set<string>();

    for (const row of rows) {
      const table = committed.tables.get(row.table_name);
      if (!table) continue; // the table test above already reports this
      seen.add(`${row.table_name}.${row.column_name}`);

      const column = table.get(row.column_name);
      if (!column) {
        differences.push(`${row.table_name}.${row.column_name} is missing from the types`);
        continue;
      }
      const cls = typeClass(row.data_type, row.udt_name, enums);
      if (classesDiffer(cls, column.cls)) {
        differences.push(
          `${row.table_name}.${row.column_name}: database says ${cls}, types say ${column.cls}`,
        );
      }
      const nullable = row.is_nullable === "YES";
      if (column.nullable !== nullable) {
        differences.push(
          `${row.table_name}.${row.column_name}: database says ${
            nullable ? "nullable" : "not null"
          }, types say ${column.nullable ? "nullable" : "not null"}`,
        );
      }
    }

    for (const [table, columns] of committed.tables) {
      for (const column of columns.keys()) {
        if (!seen.has(`${table}.${column}`)) {
          differences.push(`${table}.${column} is in the types but not in the database`);
        }
      }
    }

    expect(differences, REGENERATE).toEqual([]);
  });

  it("describes the same functions PostgREST can call", async () => {
    // Three things decide whether the generator lists a function, and getting
    // any of them wrong turns this guard into a source of false alarms — it
    // did twice while this test was being written. It must be in `public`; it
    // must not return `trigger`, because PostgREST cannot call those; and
    // `anon` or `authenticated` must be able to execute it. 0006 revokes
    // execute on two of these deliberately, and their absence from the
    // generated file is correct rather than drift.
    expect(await exposedFunctions(db), REGENERATE).toEqual(
      [...committed.functions].sort(),
    );
  });
});
