import { describe, expect, it } from "vitest";
import { expectParserError } from "./helpers/expect-parser-error";
import {
  isPractiscorePdfFormat,
  parsePractiscorePdfText,
  type PractiscorePdfPage,
} from "@/lib/parsers/practiscore-pdf";

/**
 * Fixtures basados en la salida real de `extractPdfPages` (unpdf) para los
 * PDFs que exporta la app PractiScore — caso "TFMDP 2do Social Escopeta".
 *
 * Los tests corren contra `parsePractiscorePdfText` (pure function). El
 * binding con unpdf se valida en el navegador cuando el usuario sube el PDF.
 */

const overallPage = `TFMDP 2do Social Escopeta - 2026-04-25
Match Results - Classic Manual
Match
Place Name No. Class Div PF Category Match % Region
Pts
1 Godoy, Gabriel CM Maj 460.0000 100.0000% MDP
Match Results - Open
Match
Place Name No. Class Div PF Category Match % Region
Pts
1 San Miguel, Rodrigo O Maj 448.2239 100.0000% MDP
2 Saumel, Carlos U O Maj Senior 408.6928 91.1805% MDP-ARG
3 San Miguel, Eduardo O Maj Grand Senior 246.1888 54.9254% BSAS
Match Results - Standard
Match
Place Name No. Class Div PF Category Match % Region
Pts
1 Pons, Hernan S Maj Senior 420.0000 100.0000% BSAS
2 Staltari, Gaston U S Maj 335.1989 79.8093% MDP
3 Muñiz, Gabriel 698 U S Maj 327.6212 78.0050% ARG-MDP
4 Annuassi Castañon Hurtado, Santiago S Maj 321.2550 76.4893%
Super Senior,
5 Calzoni, Mingo S Maj 186.1204 44.3144% MDP
Grand Senior
Super Senior,
6 (DQ) Bodega, Jose Luis S Maj BCE
Grand Senior
Match Results - Standard Manual
Match
Place Name No. Class Div PF Category Match % Region
Pts
1 Staltari, Martin U SM Maj 460.0000 100.0000% ARG-MDP
2 Amunategui, Carlos SM Maj Senior 348.1215 75.6786% BCE
Generated by PractiScore 2.3.7+309 samsung SM-S918B at Apr 25, 2026 19:12`;

const stage1Page = `TFMDP 2do Social Escopeta - Stage 1 Campo 4A - 2026-04-25
Stage Results - Classic Manual
Hit Stage
Place Name No. Class Div PF Points Pen Time Stage %
Factor Pts
1 Godoy, Gabriel CM Maj 80 0 60.05 1.3322 80.0000 100.00%
Stage Results - Open
Hit Stage
Place Name No. Class Div PF Points Pen Time Stage %
Factor Pts
1 San Miguel, Rodrigo O Maj 80 0 19.92 4.0161 80.0000 100.00%
2 Saumel, Carlos U O Maj 80 0 24.92 3.2103 63.9486 79.94%
3 San Miguel, Eduardo O Maj 80 0 37.47 2.1350 42.5300 53.16%
Stage Results - Standard
Hit Stage
Place Name No. Class Div PF Points Pen Time Stage %
Factor Pts
1 Pons, Hernan S Maj 80 0 21.31 3.7541 80.0000 100.00%
2 Staltari, Gaston U S Maj 80 0 27.78 2.8798 61.3679 76.71%
5 Calzoni, Mingo S Maj 65 60 33.01 0.1515 3.2278 4.03%
6 (DQ) Bodega, Jose Luis S Maj
Stage Results - Standard Manual
Hit Stage
Place Name No. Class Div PF Points Pen Time Stage %
Factor Pts
1 Staltari, Martin U SM Maj 80 0 23.62 3.3870 80.0000 100.00%
Generated by PractiScore 2.3.7+309 samsung SM-S918B at Apr 25, 2026 19:15`;

const stage2Page = `TFMDP 2do Social Escopeta - Stage 2 Campo 6 - 2026-04-25
Stage Results - Open
Hit Stage
Place Name No. Class Div PF Points Pen Time Stage %
Factor Pts
1 San Miguel, Rodrigo O Maj 85 0 15.02 5.6591 85.0000 100.00%
2 Saumel, Carlos U O Maj 85 0 17.40 4.8851 73.3736 86.32%
Generated by PractiScore 2.3.7+309 samsung SM-S918B at Apr 25, 2026 19:16`;

// Página SIN número de stage en el título (caso real "Campo 4B").
const stageNoNumberPage = `TFMDP 2do Social Escopeta - Campo 4B - 2026-04-25
Stage Results - Open
Hit Stage
Place Name No. Class Div PF Points Pen Time Stage %
Factor Pts
1 San Miguel, Rodrigo O Maj 80 0 14.74 5.4274 80.0000 100.00%
2 Saumel, Carlos U O Maj 80 0 18.61 4.2988 63.3638 79.20%
Generated by PractiScore 2.3.7+309 samsung SM-S918B at Apr 25, 2026 19:16`;

// PractiScore para Android: el título usa "Ejercicio N" (no "Stage N Campo
// X") y un stage con muchas divisiones se desborda a una 2da página física
// que NO repite el título (empieza directo con filas / un section header).
// La división "Standard" queda partida entre las dos páginas a propósito.
const ejercicio1Page1 = `TP TEST ESCOPETA - Ejercicio 1 - 2026-06-20
Stage Results - Open
1 Open, Uno O Maj 65 0 13.41 4.8471 65.0000 100.00%
Stage Results - Standard
1 Std, Uno S Maj 65 0 14.70 4.4218 65.0000 100.00%
Generated by PractiScore for Android (1.7.36 motorola) at 2026-06-20 14:01 -0300`;

// Continuación: SIN título. Arranca con una fila de Standard (la división
// partida) y luego abre Standard Manual.
const ejercicio1Page2 = `2 Std, Dos S Maj 65 0 18.09 3.5931 52.8192 81.26%
Stage Results - Standard Manual
1 SM, Uno SM Maj 65 0 17.90 3.6313 65.0000 100.00%
Generated by PractiScore for Android (1.7.36 motorola) at 2026-06-20 14:01 -0300`;

const ejercicio2Page1 = `TP TEST ESCOPETA - Ejercicio 2 - 2026-06-20
Stage Results - Open
1 Open, Uno O Maj 40 0 10.74 3.7244 40.0000 100.00%
Generated by PractiScore for Android (1.7.36 motorola) at 2026-06-20 14:02 -0300`;

function pages(...texts: string[]): PractiscorePdfPage[] {
  return texts.map((text, i) => ({ num: i + 1, text }));
}

/** Página de stage mínima con un descriptor de título arbitrario. */
function stagePage(descriptor: string): string {
  return `TFMDP 2do Social Escopeta - ${descriptor} - 2026-04-25
Stage Results - Open
Hit Stage
Place Name No. Class Div PF Points Pen Time Stage %
Factor Pts
1 San Miguel, Rodrigo O Maj 80 0 19.92 4.0161 80.0000 100.00%
Generated by PractiScore 2.3.7+309 samsung SM-S918B at Apr 25, 2026 19:16`;
}

describe("isPractiscorePdfFormat", () => {
  it("detecta por footer 'Generated by PractiScore' + header de sección", () => {
    expect(isPractiscorePdfFormat(overallPage)).toBe(true);
    expect(isPractiscorePdfFormat(stage1Page)).toBe(true);
  });

  it("rechaza PDFs sin marcadores de PractiScore", () => {
    expect(isPractiscorePdfFormat("Some random PDF text")).toBe(false);
    // Tiene el header de sección pero no el footer de PractiScore.
    expect(isPractiscorePdfFormat("Match Results - Open\n1 Foo, Bar O Maj")).toBe(
      false,
    );
  });
});

describe("parsePractiscorePdfText — overall", () => {
  it("extrae nombre, fecha y disciplina del título", () => {
    const parsed = parsePractiscorePdfText(pages(overallPage));
    expect(parsed.name).toBe("TFMDP 2do Social Escopeta");
    expect(parsed.date).toBe("2026-04-25");
    expect(parsed.discipline).toBe("ipsc");
    expect(parsed.source).toBe("practiscore_pdf");
    expect(parsed.generatedBy).toBe("PractiScore");
  });

  it("mapea las divisiones de escopeta a sus codes", () => {
    const parsed = parsePractiscorePdfText(pages(overallPage));
    const codes = new Set(parsed.matchEntries.map((e) => e.divisionCode));
    expect(codes).toEqual(new Set(["CM", "O", "S", "SM"]));
  });

  it("parsea decimales con punto y % (460.0000, 100.0000%)", () => {
    const parsed = parsePractiscorePdfText(pages(overallPage));
    const godoy = parsed.matchEntries.find(
      (e) => e.shooter.fullName === "Godoy, Gabriel",
    );
    expect(godoy?.matchPoints).toBe(460);
    expect(godoy?.matchPercentage).toBe(100);
    expect(godoy?.divisionCode).toBe("CM");
    expect(godoy?.powerFactor).toBe("Maj");
  });

  it("pela los tokens de columna (No./Class/Div) del nombre", () => {
    const parsed = parsePractiscorePdfText(pages(overallPage));
    // "Muñiz, Gabriel 698 U S Maj ..." → nombre limpio sin 698/U/S.
    const muniz = parsed.matchEntries.find((e) =>
      e.shooter.fullName.startsWith("Muñiz"),
    );
    expect(muniz?.shooter.fullName).toBe("Muñiz, Gabriel");
    expect(muniz?.matchPoints).toBe(327.6212);
    expect(muniz?.shooter.region).toBe("ARG-MDP");
  });

  it("marca DQ por prefijo (DQ) y no le asigna puntaje", () => {
    const parsed = parsePractiscorePdfText(pages(overallPage));
    const bodega = parsed.matchEntries.find((e) =>
      e.shooter.fullName.startsWith("Bodega"),
    );
    expect(bodega?.isDq).toBe(true);
    expect(bodega?.place).toBe(0);
    expect(bodega?.matchPoints).toBe(0);
    expect(bodega?.shooter.region).toBe("BCE");
  });

  it("captura la categoría cuando está inline con la fila", () => {
    const parsed = parsePractiscorePdfText(pages(overallPage));
    const saumel = parsed.matchEntries.find((e) =>
      e.shooter.fullName.startsWith("Saumel"),
    );
    expect(saumel?.category).toBe("Senior");
  });

  it("parsea filas con region multi-palabra sin marcarlas ausentes", () => {
    // Regresión: una region con espacios ("NECOCHEA -ARG", "MAR DEL PLATA-ARG")
    // rompía el regex de score anclado a `$`, mandaba la fila al branch
    // sin-puntaje y la marcaba Ausente pese a tener pts/%. Caso real:
    // "2do. Torneo Social IPSC (clone)" (Necochea).
    const page = `2do. Torneo Social IPSC (clone) - 2026-06-14
Match Results - Production
Place Name No. Class Div PF Category Match Pts Match % Region
1 Soler, Leandro P Min 407.8793 100.0000% NECOCHEA -ARG
3 Moreno, Maria De Los Angeles P Min Lady Senior 273.7632 67.1187% MAR DEL PLATA-ARG
11 Jurado, Pablo P Min 201.4057 49.3788% CURSANTE-ARG
28 (DQ) Iglesias, Pablo P Min CURSANTE
Generated by PractiScore 2.3.11+313 iPhone 26.5.1 at Jun 16, 2026 12:14`;
    const parsed = parsePractiscorePdfText(pages(page));

    const soler = parsed.matchEntries.find((e) =>
      e.shooter.fullName.startsWith("Soler"),
    );
    expect(soler?.isAbsent).toBe(false);
    expect(soler?.matchPoints).toBe(407.8793);
    expect(soler?.matchPercentage).toBe(100);
    // Region normalizada: "NECOCHEA -ARG" (espacio antes del guion) → "NECOCHEA-ARG".
    expect(soler?.shooter.region).toBe("NECOCHEA-ARG");

    // Categoría multi-palabra + region multi-palabra en la misma fila.
    const moreno = parsed.matchEntries.find((e) =>
      e.shooter.fullName.startsWith("Moreno"),
    );
    expect(moreno?.isAbsent).toBe(false);
    expect(moreno?.matchPoints).toBe(273.7632);
    expect(moreno?.category).toBe("Lady Senior");
    expect(moreno?.shooter.region).toBe("MAR DEL PLATA-ARG");

    // Single-token region sigue OK; DQ sigue siendo DQ (no ausente).
    const jurado = parsed.matchEntries.find((e) =>
      e.shooter.fullName.startsWith("Jurado"),
    );
    expect(jurado?.isAbsent).toBe(false);
    expect(jurado?.shooter.region).toBe("CURSANTE-ARG");

    const iglesias = parsed.matchEntries.find((e) =>
      e.shooter.fullName.startsWith("Iglesias"),
    );
    expect(iglesias?.isDq).toBe(true);
    expect(iglesias?.isAbsent).toBe(false);

    expect(parsed.matchEntries.filter((e) => e.isAbsent)).toHaveLength(0);
  });
});

describe("parsePractiscorePdfText — stages", () => {
  it("parsea las 6 columnas del stage (points/pen/time/factor/pts/%)", () => {
    const parsed = parsePractiscorePdfText(pages(stage1Page));
    const stage = parsed.stages.find((s) => s.stageNumber === 1)!;
    const calzoni = stage.results.find((r) =>
      r.shooter.fullName.startsWith("Calzoni"),
    );
    expect(calzoni?.points).toBe(65);
    expect(calzoni?.penalties).toBe(60);
    expect(calzoni?.timeSeconds).toBe(33.01);
    expect(calzoni?.hitFactor).toBe(0.1515);
    expect(calzoni?.stagePoints).toBe(3.2278);
    expect(calzoni?.stagePercentage).toBe(4.03);
  });

  it("marca DQ del stage sin columnas numéricas", () => {
    const parsed = parsePractiscorePdfText(pages(stage1Page));
    const stage = parsed.stages.find((s) => s.stageNumber === 1)!;
    const bodega = stage.results.find((r) =>
      r.shooter.fullName.startsWith("Bodega"),
    );
    expect(bodega?.isDq).toBe(true);
    expect(bodega?.place).toBe(0);
    expect(bodega?.stagePoints).toBe(0);
    expect(bodega?.hitFactor).toBeNull();
  });

  it("usa el número de stage explícito del título", () => {
    const parsed = parsePractiscorePdfText(pages(stage1Page, stage2Page));
    expect(parsed.stages.map((s) => s.stageNumber)).toEqual([1, 2]);
  });

  it("infiere el stage sin número por orden de página (Campo 4B → 3)", () => {
    // Páginas: Stage 1, Stage 2, Campo 4B (sin número). El candidato por
    // orden de página (3) está libre → stage 3.
    const parsed = parsePractiscorePdfText(
      pages(stage1Page, stage2Page, stageNoNumberPage),
    );
    expect(parsed.stages.map((s) => s.stageNumber)).toEqual([1, 2, 3]);
  });

  it("cae a 'stage anterior + 1' cuando el orden de página ya está tomado", () => {
    // Stage 3 (idx 1, used={3}), Stage 4 (idx 2, used={3,4}), sin-número
    // (idx 3): candidato A = orden de página = 3 → ocupado; candidato B =
    // prev(4) + 1 = 5 → libre → 5.
    const parsed = parsePractiscorePdfText(
      pages(stagePage("Stage 3 Campo A"), stagePage("Stage 4 Campo B"), stagePage("Campo C")),
    );
    expect(parsed.stages.map((s) => s.stageNumber)).toEqual([3, 4, 5]);
  });

  it("aborta si el orden de página y stage+1 ya están ocupados", () => {
    // Stage 3 (idx 1, used={3}), Stage 2 (idx 2, used={3,2}), sin-número
    // (idx 3): candidato A = 3 → ocupado; candidato B = prev(2) + 1 = 3 →
    // ocupado → error.
    expectParserError(
      () =>
        parsePractiscorePdfText(
          pages(
            stagePage("Stage 3 Campo A"),
            stagePage("Stage 2 Campo B"),
            stagePage("Campo C"),
          ),
        ),
      "stageSlotTaken",
    );
  });

  it("aborta si dos páginas declaran el mismo número de stage explícito", () => {
    expectParserError(
      () =>
        parsePractiscorePdfText(
          pages(stagePage("Stage 2 Campo A"), stagePage("Stage 2 Campo B")),
        ),
      "duplicateStageNumber",
      { stage: 2 },
    );
  });

  // PractiScore para Android: "Ejercicio N" + stages multi-página.
  it("toma el número de 'Ejercicio N' del título (Android)", () => {
    const parsed = parsePractiscorePdfText(pages(ejercicio2Page1));
    expect(parsed.name).toBe("TP TEST ESCOPETA");
    expect(parsed.stages.map((s) => s.stageNumber)).toEqual([2]);
    expect(parsed.stages[0]!.name).toBe("Ejercicio 2");
  });

  it("no parte un stage en dos por su 2da página de continuación", () => {
    // Ejercicio 1 abarca 2 páginas; la 2da no trae título. Debe quedar UN
    // solo stage (#1), no dos.
    const parsed = parsePractiscorePdfText(
      pages(ejercicio1Page1, ejercicio1Page2),
    );
    expect(parsed.stages.map((s) => s.stageNumber)).toEqual([1]);
  });

  it("rejunta una división partida por el salto de página y suma las divisiones de la pág 2", () => {
    const parsed = parsePractiscorePdfText(
      pages(ejercicio1Page1, ejercicio1Page2),
    );
    const results = parsed.stages[0]!.results;
    // Standard tenía 1 fila en la pág 1 y 1 en la pág 2 (continuación sin
    // header): las dos tienen que estar.
    const standard = results.filter((r) => r.divisionCode === "S");
    expect(standard.length).toBe(2);
    // Divisiones de ambas páginas presentes (Open + Standard en pág 1,
    // Standard Manual en pág 2).
    const divs = new Set(results.map((r) => r.divisionCode));
    expect([...divs].sort()).toEqual(["O", "S", "SM"]);
  });

  it("dos ejercicios en un mismo archivo → stages numerados por título", () => {
    const parsed = parsePractiscorePdfText(
      pages(ejercicio1Page1, ejercicio1Page2, ejercicio2Page1),
    );
    expect(parsed.stages.map((s) => s.stageNumber)).toEqual([1, 2]);
  });
});
