import { describe, expect, it } from "vitest";
import {
  isSteelChallengePdfFormat,
  parseSteelChallengePdfs,
  type SteelPdfFile,
} from "@/lib/parsers/steel-challenge-pdf";

/**
 * Fixtures sintéticos basados en la salida real del extractor de PDFs
 * (`reconstructTextByPosition`) sobre los archivos PractiScore iPhone de
 * Steel Challenge.
 *
 * Cubren los dos sub-formatos relevantes:
 *   - "Stage Results - By Division" (un archivo por stage, con secciones
 *     Pcc y Pistola dentro).
 *   - "Category Leaders - <División>" (ignorados por el parser pero
 *     usados para validar la detección + error de "solo Category Leaders").
 *
 * Mantenemos el texto inline en lugar de subir PDFs al repo: los tests
 * corren contra `parseSteelChallengePdfs` (pure function), y el binding
 * con `unpdf` se valida cuando el usuario sube un PDF real.
 */

const stage1Text = `Steel Challenge
2026-05-29
Stage Results - By Division
Pcc - Stage 1 (Cancha 3)
Final Name USPSA# Division Time % String 1 String 2 String 3 TOD Raw P Raw P Raw P
1 Ferraro, Martin P 6.36 100.00 3.49 3.37 2.99 06-13 12:22
2 Battaglino, Sebastian P 6.97 91.25 3.41 2.28 9.00 3.56 06-13 12:40
3 Alzatto, Luciano P 6.99 90.99 3.13 4.92 3.86 06-13 12:38
Pistola - Stage 1 (Cancha 3)
Final Name USPSA# Division Time % String 1 String 2 String 3 TOD Raw P Raw P Raw P
1 Alzatto, Luciano P 12.47 100.00 7.83 6.60 5.87 06-13 12:18
2 FLORES, Nicolas P 15.32 81.40 5.88 11.65 9.44 06-13 12:24
3 Battaglino, Guido P 15.55 80.19 6.52 9.81 9.03 06-13 12:05
Generated by PractiScore 2.3.11+313 iPhone 26.5 at Jun 13, 2026 13:28`;

const stage2Text = `Steel Challenge
2026-05-29
Stage Results - By Division
Pcc - Stage 2 (Cancha 4)
Final Name USPSA# Division Time % String 1 String 2 String 3 TOD Raw P Raw P Raw P
1 Alzatto, Luciano P 5.91 100.00 2.93 5.56 2.98 06-13 11:42
2 Ferraro, Martin P 6.53 90.51 4.01 3.21 3.32 06-13 11:28
3 Battaglino, Sebastian P 7.41 79.76 3.69 3.90 3.72 06-13 11:43
Pistola - Stage 2 (Cancha 4)
Final Name USPSA# Division Time % String 1 String 2 String 3 TOD Raw P Raw P Raw P
1 FLORES, Nicolas P 10.03 100.00 4.83 5.20 6.17 06-13 11:30
2 Alzatto, Luciano P 11.73 85.51 6.14 5.64 6.09 06-13 11:25
3 Battaglino, Guido P 15.29 65.60 7.19 13.43 8.10 06-13 11:14
Generated by PractiScore 2.3.11+313 iPhone 26.5 at Jun 13, 2026 13:28`;

const stage3Text = `Steel Challenge
2026-05-29
Stage Results - By Division
Pcc - Stage 3 (Cancha 5)
Final Name USPSA# Division Time % String 1 String 2 String 3 TOD Raw P Raw P Raw P
1 Alzatto, Luciano P 7.43 100.00 4.36 3.89 3.54 06-13 10:51
2 Ferraro, Martin P 7.56 98.28 3.90 3.66 4.15 06-13 10:32
3 Battaglino, Sebastian P 12.05 61.66 4.08 7.97 30.00 06-13 10:53
Pistola - Stage 3 (Cancha 5)
Final Name USPSA# Division Time % String 1 String 2 String 3 TOD Raw P Raw P Raw P
1 Alzatto, Luciano P 12.37 100.00 6.82 5.90 6.47 06-13 10:27
2 FLORES, Nicolas P 14.78 83.69 6.07 10.76 8.71 06-13 10:34
3 Battaglino, Guido P 28.41 43.54 13.37 30.00 15.04 06-13 10:15
Generated by PractiScore 2.3.11+313 iPhone 26.5 at Jun 13, 2026 13:29`;

const categoryLeadersPistolaText = `Steel Challenge
2026-05-29
Category Leaders - Pistola
Category: Deportivo
Final Name USPSA# Division Time % 1:
Cancha 3
2:
Cancha 4
3:
Cancha 5
1 Alzatto, Luciano P 36.57 100.00 12.47 11.73 12.37
2 FLORES, Nicolas P 40.13 91.13 15.32 10.03 14.78
Category: General
Final Name USPSA# Division Time % 1:
Cancha 3
2:
Cancha 4
3:
Cancha 5
1 Battaglino, Guido P 59.25 75.76 15.55 15.29 28.41
Generated by PractiScore 2.3.11+313 iPhone 26.5 at Jun 13, 2026 12:59`;

function asPdfFile(filename: string, text: string): SteelPdfFile {
  return {
    filename,
    pages: [{ num: 1, text }],
  };
}

describe("isSteelChallengePdfFormat", () => {
  it("acepta 'Stage Results - By Division' con Steel Challenge", () => {
    expect(isSteelChallengePdfFormat(stage1Text)).toBe(true);
  });

  it("acepta 'Category Leaders' con Steel Challenge", () => {
    expect(isSteelChallengePdfFormat(categoryLeadersPistolaText)).toBe(true);
  });

  it("rechaza texto que no menciona Steel Challenge", () => {
    expect(isSteelChallengePdfFormat("WinMSS overall page")).toBe(false);
  });

  it("rechaza Steel Challenge sin header reconocible", () => {
    expect(isSteelChallengePdfFormat("Steel Challenge\n2026-05-29\n")).toBe(false);
  });
});

describe("parseSteelChallengePdfs — happy path con 3 stages", () => {
  it("computa overall sumando los tiempos de los 3 stages, por división", () => {
    const result = parseSteelChallengePdfs([
      asPdfFile("stage1.pdf", stage1Text),
      asPdfFile("stage2.pdf", stage2Text),
      asPdfFile("stage3.pdf", stage3Text),
    ]);

    expect(result.discipline).toBe("steel_challenge");
    expect(result.source).toBe("practiscore_steel_pdf");
    expect(result.date).toBe("2026-05-29");
    expect(result.stages).toHaveLength(3);
    expect(result.stages.map((s) => s.stageNumber)).toEqual([1, 2, 3]);

    // Alzatto en PISTOLA: 12.47 + 11.73 + 12.37 = 36.57s (líder).
    const alzatto = result.matchEntries.find(
      (e) =>
        e.shooter.fullName === "Alzatto, Luciano" && e.divisionCode === "PISTOLA",
    );
    expect(alzatto).toBeDefined();
    expect(alzatto!.totalTimeSeconds).toBeCloseTo(36.57, 2);
    expect(alzatto!.place).toBe(1);
    expect(alzatto!.matchPercentage).toBeCloseTo(100, 2);

    // FLORES en PISTOLA: 15.32 + 10.03 + 14.78 = 40.13s → % = 36.57/40.13*100
    const flores = result.matchEntries.find(
      (e) =>
        e.shooter.fullName === "FLORES, Nicolas" && e.divisionCode === "PISTOLA",
    );
    expect(flores).toBeDefined();
    expect(flores!.totalTimeSeconds).toBeCloseTo(40.13, 2);
    expect(flores!.place).toBe(2);
    expect(flores!.matchPercentage).toBeCloseTo((36.57 / 40.13) * 100, 1);
  });

  it("rankea PCC y PISTOLA por separado (no mezclados)", () => {
    const result = parseSteelChallengePdfs([
      asPdfFile("stage1.pdf", stage1Text),
      asPdfFile("stage2.pdf", stage2Text),
      asPdfFile("stage3.pdf", stage3Text),
    ]);

    // Cada división tiene su propio set de places empezando en 1.
    const pccPlaces = result.matchEntries
      .filter((e) => e.divisionCode === "PCC" && !e.isAbsent)
      .map((e) => e.place);
    const pistolaPlaces = result.matchEntries
      .filter((e) => e.divisionCode === "PISTOLA" && !e.isAbsent)
      .map((e) => e.place);
    expect(pccPlaces).toContain(1);
    expect(pistolaPlaces).toContain(1);
  });

  it("genera stage_results con place y % por stage dentro de cada división", () => {
    const result = parseSteelChallengePdfs([
      asPdfFile("stage1.pdf", stage1Text),
      asPdfFile("stage2.pdf", stage2Text),
      asPdfFile("stage3.pdf", stage3Text),
    ]);

    const stage1 = result.stages.find((s) => s.stageNumber === 1)!;
    // 6 tiradores en stage 1 (3 PCC + 3 Pistola).
    expect(stage1.results).toHaveLength(6);

    const ferraroStage1 = stage1.results.find(
      (r) => r.shooter.fullName === "Ferraro, Martin",
    )!;
    expect(ferraroStage1.timeSeconds).toBeCloseTo(6.36, 2);
    expect(ferraroStage1.stagePercentage).toBeCloseTo(100, 2);
    expect(ferraroStage1.place).toBe(1);
    expect(ferraroStage1.divisionCode).toBe("PCC");
  });
});

describe("parseSteelChallengePdfs — error paths", () => {
  it("error claro si solo se suben Category Leaders sin Stage Results", () => {
    expect(() =>
      parseSteelChallengePdfs([
        asPdfFile("leaders.pdf", categoryLeadersPistolaText),
      ]),
    ).toThrowError(/Stage Results - By Division/);
  });

  it("error si se suben dos archivos del mismo stage (data duplicada)", () => {
    expect(() =>
      parseSteelChallengePdfs([
        asPdfFile("stage1.pdf", stage1Text),
        asPdfFile("stage1-dup.pdf", stage1Text),
      ]),
    ).toThrowError(/stage 1/i);
  });

  it("error si no se recibe ningún archivo", () => {
    expect(() => parseSteelChallengePdfs([])).toThrow();
  });
});

describe("parseSteelChallengePdfs — single stage", () => {
  it("acepta un solo stage y rankea ese stage como overall", () => {
    const result = parseSteelChallengePdfs([
      asPdfFile("stage1.pdf", stage1Text),
    ]);

    expect(result.stages).toHaveLength(1);
    expect(result.matchEntries.length).toBeGreaterThan(0);

    // Con un solo stage, totalStages = 1 — todos compitieron en él.
    // El overall es básicamente ese único stage time por tirador.
    const alzatto = result.matchEntries.find(
      (e) =>
        e.shooter.fullName === "Alzatto, Luciano" && e.divisionCode === "PISTOLA",
    )!;
    expect(alzatto.totalTimeSeconds).toBeCloseTo(12.47, 2);
    expect(alzatto.isAbsent).toBe(false);
    expect(alzatto.place).toBe(1);
  });
});

describe("parseSteelChallengePdfs — categorías desde Category Leaders", () => {
  it("rellena `category` cuando se sube también un PDF de Category Leaders", () => {
    const result = parseSteelChallengePdfs([
      asPdfFile("stage1.pdf", stage1Text),
      asPdfFile("stage2.pdf", stage2Text),
      asPdfFile("stage3.pdf", stage3Text),
      asPdfFile("category-leaders-pistola.pdf", categoryLeadersPistolaText),
    ]);

    const alzatto = result.matchEntries.find(
      (e) =>
        e.shooter.fullName === "Alzatto, Luciano" && e.divisionCode === "PISTOLA",
    );
    expect(alzatto?.category).toBe("Deportivo");

    const guido = result.matchEntries.find(
      (e) =>
        e.shooter.fullName === "Battaglino, Guido" && e.divisionCode === "PISTOLA",
    );
    expect(guido?.category).toBe("General");
  });

  it("category queda null cuando NO se sube Category Leaders", () => {
    const result = parseSteelChallengePdfs([
      asPdfFile("stage1.pdf", stage1Text),
      asPdfFile("stage2.pdf", stage2Text),
      asPdfFile("stage3.pdf", stage3Text),
    ]);

    const alzatto = result.matchEntries.find(
      (e) =>
        e.shooter.fullName === "Alzatto, Luciano" && e.divisionCode === "PISTOLA",
    );
    expect(alzatto?.category).toBeNull();
  });
});

describe("parseSteelChallengePdfs — tiradores que faltaron a algún stage", () => {
  it("marca como ausentes a los que no compitieron en todos los stages", () => {
    // Stage 1 trae a Pinola/Lopez/Lorenzo/Timberi en PCC; stage 2 y 3 acotados
    // a solo 3 tiradores cada uno. Los que aparecen en 1 pero no en los otros
    // dos deberían quedar como `isAbsent: true`.
    const result = parseSteelChallengePdfs([
      asPdfFile("stage1.pdf", stage1Text),
      asPdfFile("stage2.pdf", stage2Text),
      asPdfFile("stage3.pdf", stage3Text),
    ]);

    // Ferraro corrió Pcc en stages 1 y 2 y 3 (presente en los 3) → no ausente.
    const ferraro = result.matchEntries.find(
      (e) => e.shooter.fullName === "Ferraro, Martin" && e.divisionCode === "PCC",
    );
    expect(ferraro?.isAbsent).toBe(false);

    // Battaglino Guido en PISTOLA corrió los 3 stages.
    const guido = result.matchEntries.find(
      (e) =>
        e.shooter.fullName === "Battaglino, Guido" && e.divisionCode === "PISTOLA",
    );
    expect(guido?.isAbsent).toBe(false);
  });
});
