import { DISCIPLINE } from "../disciplines";
import type {
  ParsedMatch,
  ParsedMatchEntry,
  ParsedStage,
  ParsedStageResult,
  PowerFactor,
} from "../types/match";
import {
  extractClubFromTitle,
  stripDqPrefix,
  stripNameSuffixes,
} from "./shared";

/**
 * Parser para los PDFs que genera la app **PractiScore** (Android/iOS) al
 * exportar resultados de un torneo IPSC. Footer característico:
 * "Generated by PractiScore 2.3.7+309 samsung SM-S918B at ...".
 *
 * Es un formato distinto de los WinMSS de ipsc.org.ar (`winmss-pdf.ts`):
 *  - Headers de sección `Match Results - <División>` / `Stage Results -
 *    <División>` en lugar de `<División> -- Overall Match Results`.
 *  - Decimales con punto (en-US) en vez de coma.
 *  - Match % / Stage % traen el signo `%`.
 *  - Fecha ISO embebida en el título: `... - 2026-04-25`.
 *  - DQ marcado con prefijo `(DQ)` antes del nombre (igual que el HTML).
 *
 * Soporta los dos archivos que exporta la app, con la misma estructura
 * interna:
 *  - **Overall**: una sola página, una sección por división con el ranking
 *    general del match.
 *  - **Stages**: una página por stage, cada una con una sección por
 *    división y las columnas de tiempo/factor/puntos del stage.
 *
 * El usuario sube los dos PDFs por separado: el overall crea el match, el
 * stages se mergea vía el path de re-upload que ya usan Steel/FBI/WinMSS.
 *
 * Diseño: `parsePractiscorePdfText(pages)` es pure — recibe páginas ya
 * extraídas a texto. La extracción del binario la hace `extractPdfPages`
 * (compartida con WinMSS/FAT) y la dispara `parsePdfBatch` (ver `index.ts`).
 */

/** Una página de un PDF, ya extraída a texto plano. */
export interface PractiscorePdfPage {
  num: number;
  text: string;
}

/**
 * Mapea el nombre de la división tal como aparece en el header de sección
 * (texto en inglés, title-case) al `code` de la tabla `divisions` de IPSC.
 *
 * El lookup se hace en MAYÚSCULAS. Si aparece una división no listada, la
 * sección se ignora con un warning y el resto del archivo sigue importándose.
 */
const DIVISION_NAME_TO_CODE: Record<string, string> = {
  OPEN: "O",
  PRODUCTION: "P",
  "PRODUCTION OPTICS": "PO",
  STANDARD: "S",
  "STANDARD MANUAL": "SM",
  "CARRY OPTICS": "CO",
  REVOLVER: "R",
  CLASSIC: "CL",
  // Escopeta: PractiScore exporta "Classic Manual" como división propia.
  // Ver migración 0017 — el code `CM` no existía (distinto de `CL` Classic).
  "CLASSIC MANUAL": "CM",
  MODIFIED: "MS",
  "MODIFIED SHOTGUN": "MS",
  PCC: "PCC",
  "PCC OPTICS": "PCCO",
  "PISTOL CALIBER CARBINE": "PCC",
  "PISTOL CALIBER CARBINE OPTICS": "PCCO",
  PISTOLA: "PIS",
};

// Tokens cortos que aparecen como columnas entre el nombre y la PF
// (No. = dorsal, Class = clasificación, Div = división). Los pelamos del
// final del nombre. La división real ya la sabemos por el section header,
// así que acá solo los descartamos.
const KNOWN_CLASSIFICATIONS = new Set(["GM", "M", "A", "B", "C", "D", "U"]);
const KNOWN_DIVISION_CODES = new Set([
  "O",
  "P",
  "PO",
  "S",
  "SM",
  "CO",
  "R",
  "CL",
  "CM",
  "MS",
  "PCC",
  "PCCO",
  "PIS",
]);

/**
 * Heurística de detección. Un PDF es de PractiScore si tiene el footer
 * "Generated by PractiScore" más al menos un header de sección
 * "Match Results -" o "Stage Results -". Los dos juntos descartan otros
 * formatos sin riesgo de falso positivo (los HTML de PractiScore no llegan
 * acá — este path es solo PDFs).
 */
export function isPractiscorePdfFormat(text: string): boolean {
  if (!/Generated\s+by\s+PractiScore/i.test(text)) return false;
  return /(?:Match|Stage)\s+Results\s*-\s*\S/i.test(text);
}

/**
 * Parsea las páginas de texto de un PDF de PractiScore. Detecta por página
 * si es overall (`Match Results -`) o stage (`Stage Results -`), y mapea
 * cada sección de división a su `code`.
 */
export function parsePractiscorePdfText(
  pages: PractiscorePdfPage[],
): ParsedMatch {
  if (pages.length === 0) {
    throw new Error("PDF vacío: no se encontraron páginas.");
  }

  const matchEntries: ParsedMatchEntry[] = [];
  const stagesByNum = new Map<number, ParsedStage>();

  let matchName = "";
  let matchDate = "";

  // Estado para la inferencia del número de stage cuando el título no lo
  // trae (ver `resolveStageNumber`).
  let stagePageIndex = 0;
  let prevStageNumber: number | null = null;
  const usedStageNumbers = new Set<number>();

  for (const page of pages) {
    const isStagePage = /Stage\s+Results\s*-/i.test(page.text);
    const isOverallPage = /Match\s+Results\s*-/i.test(page.text);
    if (!isStagePage && !isOverallPage) {
      console.warn(
        `[practiscore-pdf] página ${page.num} descartada (sin "Match/Stage Results"). Texto: ${page.text
          .slice(0, 200)
          .replace(/\s+/g, " ")
          .trim()}`,
      );
      continue;
    }

    matchName = matchName || extractMatchName(page.text);
    matchDate = matchDate || extractDate(page.text);

    if (isOverallPage) {
      for (const section of splitSections(page.text, "Match Results")) {
        for (const entry of parseOverallRows(section.body)) {
          matchEntries.push({ ...entry, divisionCode: section.divisionCode });
        }
      }
      continue;
    }

    // Stage page.
    stagePageIndex++;
    const explicit = extractExplicitStageNumber(page.text);
    const stageNumber = resolveStageNumber(
      explicit,
      stagePageIndex,
      prevStageNumber,
      usedStageNumbers,
      page.num,
    );
    usedStageNumbers.add(stageNumber);
    prevStageNumber = stageNumber;

    let stage = stagesByNum.get(stageNumber);
    if (!stage) {
      stage = {
        stageNumber,
        name: extractStageName(page.text) ?? `Stage ${stageNumber}`,
        results: [],
      };
      stagesByNum.set(stageNumber, stage);
    }
    for (const section of splitSections(page.text, "Stage Results")) {
      for (const result of parseStageRows(section.body)) {
        stage.results.push({ ...result, divisionCode: section.divisionCode });
      }
    }
  }

  if (!matchName) {
    const snippet = (pages[0]?.text ?? "").slice(0, 200).replace(/\s+/g, " ");
    throw new Error(
      `No se pudo extraer el nombre del match del PDF de PractiScore. Inicio del texto: "${snippet}"`,
    );
  }
  if (!matchDate) {
    throw new Error(
      "No se pudo extraer la fecha del PDF (esperaba un título con fecha ISO 'YYYY-MM-DD').",
    );
  }
  if (matchEntries.length === 0 && stagesByNum.size === 0) {
    throw new Error(
      "El PDF se identificó como PractiScore pero no se pudo extraer ninguna fila de resultados.",
    );
  }

  const stages: ParsedStage[] = Array.from(stagesByNum.values()).sort(
    (a, b) => (a.stageNumber ?? 0) - (b.stageNumber ?? 0),
  );

  const region = extractClubFromTitle(matchName);

  return {
    discipline: DISCIPLINE.IPSC,
    source: "practiscore_pdf",
    name: matchName,
    date: matchDate,
    region,
    matchEntries,
    stages,
    generatedBy: "PractiScore",
  };
}

/**
 * Resuelve el número de stage de una página.
 *
 * Si el título lo trae explícito ("Stage N Campo X"), se usa ese — salvo
 * que ya lo hayamos visto en otra página (duplicado → datos corruptos).
 *
 * Si NO lo trae (caso real: página "Campo 4B" sin número), se infiere:
 *   1. candidato A = orden de aparición de la página de stage (1-based).
 *   2. candidato B = stage anterior + 1.
 * Se usa A; si A ya está tomado, se usa B; si ambos ya existen, se aborta.
 */
function resolveStageNumber(
  explicit: number | null,
  stagePageIndex: number,
  prevStageNumber: number | null,
  used: Set<number>,
  pageNum: number,
): number {
  if (explicit != null) {
    if (used.has(explicit)) {
      throw new Error(
        `El PDF tiene dos stages con el número ${explicit} (página ${pageNum}). No se puede importar.`,
      );
    }
    return explicit;
  }

  const candidateA = stagePageIndex;
  const candidateB = (prevStageNumber ?? 0) + 1;
  if (!used.has(candidateA)) return candidateA;
  if (!used.has(candidateB)) return candidateB;
  throw new Error(
    `No se pudo determinar el número del stage en la página ${pageNum}: ` +
      `el orden de página (${candidateA}) y el stage anterior + 1 (${candidateB}) ` +
      "ya están ocupados. ¿El PDF tiene stages repetidos o fuera de orden?",
  );
}

interface Section {
  divisionCode: string;
  body: string;
}

/**
 * Parte una página en secciones por división. Cada sección arranca en un
 * header "<kind> Results - <División>" y va hasta el próximo header (o el
 * fin de la página). Las divisiones desconocidas se descartan.
 */
function splitSections(text: string, kind: "Match Results" | "Stage Results"): Section[] {
  const headerRe = new RegExp(
    `${kind.replace(/\s+/g, "\\s+")}\\s*-\\s*(.+)`,
    "gi",
  );
  const sections: Section[] = [];
  const matches = [...text.matchAll(headerRe)];
  for (let i = 0; i < matches.length; i++) {
    const m = matches[i]!;
    const divisionRaw = m[1]!.trim().replace(/\s+/g, " ").toUpperCase();
    const start = m.index! + m[0].length;
    const end = i + 1 < matches.length ? matches[i + 1]!.index! : text.length;
    const code = DIVISION_NAME_TO_CODE[divisionRaw];
    if (!code) {
      console.warn(
        `[practiscore-pdf] división desconocida "${divisionRaw}" — sección ignorada.`,
      );
      continue;
    }
    sections.push({ divisionCode: code, body: text.slice(start, end) });
  }
  return sections;
}

/**
 * El título arranca la página: "<Nombre> - <descriptor?> - <fecha ISO>".
 * El nombre es lo que está antes del primer " - " que precede a un stage
 * descriptor o a la fecha. Pelamos la fecha y el descriptor de stage del
 * final y nos quedamos con el resto.
 */
function extractMatchName(text: string): string {
  const firstLine = text.split(/\n/)[0]?.trim() ?? "";
  if (!firstLine) return "";
  return firstLine
    .replace(/\s*-\s*\d{4}-\d{2}-\d{2}\s*$/, "")
    .replace(/\s*-\s*(?:Stage\s+\d+\b.*|Campo\b.*)$/i, "")
    .trim();
}

/** Fecha ISO YYYY-MM-DD embebida en el título. */
function extractDate(text: string): string {
  const m = /\b(\d{4}-\d{2}-\d{2})\b/.exec(text);
  return m ? m[1]! : "";
}

/**
 * Número de stage explícito del título ("... - Stage 4 Campo 13 - ..."),
 * o `null` si la página no lo trae (ej. "... - Campo 4B - ...").
 */
function extractExplicitStageNumber(text: string): number | null {
  const firstLine = text.split(/\n/)[0] ?? "";
  const m = /\bStage\s+(\d+)\b/i.exec(firstLine);
  return m ? parseInt(m[1]!, 10) : null;
}

/**
 * Nombre legible del stage tomado del descriptor del título ("Stage 4 Campo
 * 13" → "Campo 13", "Campo 4B" → "Campo 4B"). `null` si no hay descriptor.
 */
function extractStageName(text: string): string | null {
  const firstLine = text.split(/\n/)[0] ?? "";
  const m = /-\s*((?:Stage\s+\d+\s+)?Campo\b[^-]*?)\s*-\s*\d{4}-\d{2}-\d{2}/i.exec(
    firstLine,
  );
  if (!m) return null;
  return m[1]!.replace(/^Stage\s+\d+\s+/i, "").trim() || null;
}

/**
 * Normaliza la columna Region/club: colapsa espacios repetidos y saca los
 * espacios alrededor del guion que PractiScore mete en algunas planillas
 * ("NECOCHEA -ARG" → "NECOCHEA-ARG"), preservando los espacios internos del
 * nombre ("MAR DEL PLATA-ARG"). Devuelve `null` si queda vacío.
 */
function normalizeRegion(raw: string): string | null {
  const clean = raw.trim().replace(/\s+/g, " ").replace(/\s*-\s*/g, "-");
  return clean || null;
}

const PF_SPLIT_RE = /^(.*?)\s+(Maj|Min)\b\s*(.*)$/;

function parsePowerFactor(token: string): PowerFactor {
  if (/^Maj$/i.test(token)) return "Maj";
  if (/^Min$/i.test(token)) return "Min";
  return null;
}

/**
 * Pela del final los tokens de columna (No./Class/Div) que quedan pegados
 * entre el nombre y la PF, y devuelve el nombre limpio.
 */
function extractName(beforePf: string): string {
  const tokens = beforePf.trim().split(/\s+/);
  while (tokens.length > 0) {
    const t = tokens[tokens.length - 1]!;
    if (
      KNOWN_DIVISION_CODES.has(t.toUpperCase()) ||
      KNOWN_CLASSIFICATIONS.has(t.toUpperCase()) ||
      /^\d+$/.test(t)
    ) {
      tokens.pop();
      continue;
    }
    break;
  }
  return stripNameSuffixes(tokens.join(" ").trim());
}

/**
 * Filas de overall:
 *   `<place> [(DQ)] <Apellido, Nombre> [No] [Class] <Div> <PF> [Cat] <MatchPts> <Match%> [Region]`
 * Ejemplo: "2 Saumel, Carlos U O Maj Senior 408.6928 91.1805% MDP-ARG"
 *
 * Las filas DQ no traen puntaje/porcentaje: "6 (DQ) Bodega, Jose Luis S Maj BCE".
 */
function parseOverallRows(
  text: string,
): Array<Omit<ParsedMatchEntry, "divisionCode">> {
  const out: Array<Omit<ParsedMatchEntry, "divisionCode">> = [];
  for (const rawLine of text.split(/\n/)) {
    const line = rawLine.trim();
    const head = /^(\d+)\s+(.+)$/.exec(line);
    if (!head) continue;
    const place = parseInt(head[1]!, 10);
    const { fullName: afterPlace, isDq } = stripDqPrefix(head[2]!);

    const split = PF_SPLIT_RE.exec(afterPlace);
    if (!split) continue;
    const name = extractName(split[1]!);
    if (!name) continue;
    const powerFactor = parsePowerFactor(split[2]!);
    const tail = split[3]!;

    // MatchPts + Match%. Ancla SOLO en el par numérico `pts pct%`: lo que
    // queda antes es la categoría y lo que queda después es la region. La
    // region puede ser multi-palabra ("NECOCHEA -ARG", "MAR DEL PLATA-ARG"),
    // así que NO la capturamos como token único anclado a `$` — eso hacía
    // fallar el match entero y mandaba la fila al branch sin-puntaje, donde
    // pts/pct=0 la marcaban como Ausente por error.
    const score = /(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)%/.exec(tail);
    let matchPoints = 0;
    let matchPercentage = 0;
    let region: string | null = null;
    let category: string | null = null;
    if (score) {
      matchPoints = parseFloat(score[1]!);
      matchPercentage = parseFloat(score[2]!);
      region = normalizeRegion(tail.slice(score.index + score[0]!.length));
      category = tail.slice(0, score.index).trim() || null;
    } else {
      // Sin puntaje: DQ o ausente real. Lo que sobra del tail es la region.
      region = normalizeRegion(tail);
    }

    out.push({
      shooter: { fullName: name, memberNumber: null, region },
      classification: null,
      powerFactor,
      category,
      place: isDq ? 0 : place,
      matchPoints,
      matchPercentage,
      totalTimeSeconds: null,
      hits: null,
      isDq,
      isAbsent: !isDq && matchPoints === 0 && matchPercentage === 0,
    });
  }
  return out;
}

/**
 * Filas de stage:
 *   `<place> [(DQ)] <name> [No] [Class] <Div> <PF> <Points> <Pen> <Time> <HitFactor> <StagePts> <Stage%>`
 * Ejemplo: "5 Calzoni, Mingo S Maj 65 60 33.01 0.1515 3.2278 4.03%"
 *
 * Las filas DQ no traen columnas numéricas: "6 (DQ) Bodega, Jose Luis S Maj".
 */
function parseStageRows(
  text: string,
): Array<Omit<ParsedStageResult, "divisionCode">> {
  const out: Array<Omit<ParsedStageResult, "divisionCode">> = [];
  for (const rawLine of text.split(/\n/)) {
    const line = rawLine.trim();
    const head = /^(\d+)\s+(.+)$/.exec(line);
    if (!head) continue;
    const place = parseInt(head[1]!, 10);
    const { fullName: afterPlace, isDq: dqPrefix } = stripDqPrefix(head[2]!);

    const split = PF_SPLIT_RE.exec(afterPlace);
    if (!split) continue;
    const name = extractName(split[1]!);
    if (!name) continue;
    const powerFactor = parsePowerFactor(split[2]!);
    const tail = split[3]!;

    // 6 columnas: Points Pen Time HitFactor StagePts Stage%
    const cols =
      /^\s*(\d+)\s+(\d+)\s+(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)%/.exec(
        tail,
      );

    if (!cols) {
      // DQ / sin datos del stage.
      out.push({
        shooter: { fullName: name, memberNumber: null, region: null },
        classification: null,
        powerFactor,
        points: null,
        penalties: null,
        timeSeconds: null,
        hitFactor: null,
        stagePoints: 0,
        stagePercentage: 0,
        place: 0,
        hits: null,
        isDq: true,
      });
      continue;
    }

    const points = parseInt(cols[1]!, 10);
    const penalties = parseInt(cols[2]!, 10);
    const timeSeconds = parseFloat(cols[3]!);
    const hitFactor = parseFloat(cols[4]!);
    const stagePoints = parseFloat(cols[5]!);
    const stagePercentage = parseFloat(cols[6]!);
    const isDq = dqPrefix || hitFactor === 0;

    out.push({
      shooter: { fullName: name, memberNumber: null, region: null },
      classification: null,
      powerFactor,
      points,
      penalties,
      timeSeconds: timeSeconds > 0 ? timeSeconds : null,
      hitFactor: hitFactor > 0 ? hitFactor : null,
      stagePoints,
      stagePercentage,
      place: isDq ? 0 : place,
      hits: null,
      isDq,
    });
  }
  return out;
}
