import type { HTMLElement } from "node-html-parser";

/**
 * Helpers compartidos entre los parsers de PractiScore (IPSC + Steel) y FBI CSV.
 *
 * Reglas de diseño:
 *  - Solo primitivas de parseo: nada de I/O ni dependencias de DB.
 *  - Cada función tiene un comportamiento bien definido para input vacío/inválido
 *    documentado en su firma (`OrNull` vs `Or<fallback>`).
 *  - Las particularidades de cada formato (clasificación de secciones,
 *    detección de discipline) se quedan en el parser específico.
 */

// ---------------------------------------------------------------------------
// Primitivas numéricas / strings
// ---------------------------------------------------------------------------

/**
 * Devuelve el valor de la celda cuya columna se llama `key`. Si no existe,
 * devuelve `undefined` (vs string vacío) para distinguir "columna ausente"
 * de "columna presente pero vacía".
 */
export function columnValue(
  headers: string[],
  row: string[],
  key: string,
): string | undefined {
  const i = headers.findIndex((h) => h === key);
  if (i < 0) return undefined;
  return row[i]?.trim();
}

/**
 * PractiScore prefija "(DQ)" al nombre de tiradores descalificados.
 * Lo separa del nombre real y devuelve la flag `isDq`.
 */
export function stripDqPrefix(name: string): { fullName: string; isDq: boolean } {
  const m = /^\(DQ\)\s*(.+)$/.exec(name);
  if (m) return { fullName: m[1].trim(), isDq: true };
  return { fullName: name.trim(), isDq: false };
}

/** Parsea "85.3%" o "85.3" → 85.3. Vacío/inválido → 0. */
export function parsePercentage(value: string | undefined): number {
  if (!value) return 0;
  const n = Number(value.replace("%", "").trim());
  return Number.isFinite(n) ? n : 0;
}

/** Parsea string numérico. Vacío/inválido → `fallback`. */
export function parseFloatOr(value: string | undefined, fallback: number): number {
  if (value === undefined || value === "") return fallback;
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

/** Parsea string numérico. Vacío/inválido → `null`. */
export function parseFloatOrNull(value: string | undefined): number | null {
  if (value === undefined || value === "") return null;
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}

/** Parsea entero base 10. Vacío/inválido → `fallback`. */
export function parseIntOr(value: string, fallback: number): number {
  const n = parseInt(value, 10);
  return Number.isFinite(n) ? n : fallback;
}

/**
 * Parsea entero permisivo (acepta "1.0" → 1). Vacío/inválido → `null`.
 * Usado por planillas que a veces traen el puntaje como float.
 */
export function parseIntOrNull(value: string | undefined): number | null {
  if (value === undefined) return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  const n = Number(trimmed);
  return Number.isFinite(n) ? Math.trunc(n) : null;
}

/** Trim + null si queda vacío. Útil para campos opcionales tipo "región". */
export function nullIfEmpty(value: string | undefined): string | null {
  if (!value) return null;
  const trimmed = value.trim();
  return trimmed === "" ? null : trimmed;
}

// ---------------------------------------------------------------------------
// HTML (PractiScore)
// ---------------------------------------------------------------------------

/**
 * Busca el footer "Generated by PractiScore vX.Y.Z" y lo devuelve normalizado
 * (un único espacio entre tokens). Útil para identificar la versión del
 * generador en logs de import.
 */
export function extractGeneratedBy(root: HTMLElement): string | null {
  const div = root
    .querySelectorAll("div")
    .find((d) => /Generated by/i.test(d.textContent));
  return div ? div.textContent.replace(/\s+/g, " ").trim() : null;
}

/**
 * Extrae secciones de una tabla PractiScore particionada por
 * `<td class="division_head">`. Cada parser pasa un `classifyHead` que
 * decide qué metadata adjuntar a la sección (kind/title para IPSC,
 * divisionCode para Steel, etc.).
 *
 * Si `classifyHead` devuelve `null`, la cabecera se ignora pero la sección
 * actual sigue abierta — replicando el comportamiento previo de los dos
 * parsers que ignoraban silenciosamente cabeceras desconocidas.
 *
 * Una sección encadena el primer `<tr>` con `<th>` como headers y los
 * siguientes `<tr>` con `<td>` como rows, hasta el próximo `division_head`.
 */
export function extractDivisionalTableSections<TMeta>(
  root: HTMLElement,
  classifyHead: (titleText: string) => TMeta | null,
): Array<{ meta: TMeta; headers: string[]; rows: string[][] }> {
  const sections: Array<{ meta: TMeta; headers: string[]; rows: string[][] }> = [];
  let current: { meta: TMeta; headers: string[]; rows: string[][] } | null = null;

  for (const tr of root.querySelectorAll("tr")) {
    const headerCell = tr.querySelector("td.division_head");
    if (headerCell) {
      const titleText =
        headerCell.querySelector("b")?.textContent?.trim() ?? "";
      const meta = classifyHead(titleText);
      if (meta !== null) {
        if (current) sections.push(current);
        current = { meta, headers: [], rows: [] };
      }
      continue;
    }

    if (!current) continue;

    const ths = tr.querySelectorAll("th");
    if (ths.length > 0) {
      current.headers = ths.map((th) => th.textContent.trim());
      continue;
    }

    const tds = tr.querySelectorAll("td");
    if (tds.length > 0) {
      current.rows.push(tds.map((td) => td.textContent.trim()));
    }
  }

  if (current) sections.push(current);
  return sections;
}
